apiVersion: v1
kind: Service
metadata:
  name: tutor-requirement-search-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: tutor-requirement-search-service
  ports:
    - port: 80
      #      nodePort: 30081 # exposing to local, to access this service
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutor-requirement-search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutor-requirement-search-service
  template:
    metadata:
      labels:
        app: tutor-requirement-search-service
    #      annotations:
    #        prometheus.io/scrape: "true"
    #        prometheus.io/port: "8080"
    #        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: tutor-requirement-search-service
          image: vishwaghimire/tutor-requirement-search-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            # Broker: Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: kafka_BootStrapServers
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: kafka_searchServiceGroupId
            - name: KAFKA_TUTOR_REQUIREMENT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: tutor-requirement-topic

            # Caching: Redis
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: redis_password

            # Tracing: Zipkin & Sleuth
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: zipkin_url
            - name: ZIPKIN_ENABLED
              value: "true"

            # Database: Elastic Search
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: elastic_host
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: elastic_port
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: elastic_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: elastic_password

            # App Specific
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: jwt-secret-key